version: '3'
services:
  app-mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sept
      - MYSQL_USER=don
      - MYSQL_PASSWORD=123Qwe!
    ports:
      - 3306:3306
  app-main:
    image: springboot-docker-compose-app:1
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - app-mysql

    volumes:
      - /data/springboot-docker-compose-app
    expose:
      - 8080
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=myapp-mysql
      - DATABASE_USER=don
      - DATABASE_PASSWORD=123Qwe!
      - DATABASE_NAME=sept
      - DATABASE_PORT=3306